/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2ndquarterproject;

import java.awt.*;

/**
 *
 * @author Asus
 */
public class HowToPlayPattern extends javax.swing.JFrame {

    /**
     * Creates new form GameHomeScreen
     */
    public HowToPlayPattern() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitGroup = new javax.swing.ButtonGroup();
        framePanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        okayBTN = new javax.swing.JButton();
        instructionsScroll = new javax.swing.JScrollPane();
        instructionsTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        framePanel.setBackground(new java.awt.Color(42, 42, 52));
        framePanel.setPreferredSize(new java.awt.Dimension(350, 250));

        titlePanel.setBackground(new java.awt.Color(27, 28, 33));
        titlePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titleLabel.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(245, 211, 28));
        titleLabel.setText("HOW TO PLAY");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        okayBTN.setBackground(new java.awt.Color(254, 211, 28));
        okayBTN.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        okayBTN.setText("OKAY");
        okayBTN.setFocusPainted(false);
        okayBTN.setFocusable(false);
        okayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayBTNActionPerformed(evt);
            }
        });

        instructionsTA.setEditable(false);
        instructionsTA.setBackground(new java.awt.Color(42, 42, 52));
        instructionsTA.setColumns(20);
        instructionsTA.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        instructionsTA.setForeground(new java.awt.Color(245, 211, 28));
        instructionsTA.setLineWrap(true);
        instructionsTA.setRows(5);
        instructionsTA.setText("               5 SECONDS TO MEMORIZE THE \n          PATTERN, THEN TRY TO FOLLOW IT.\n                  THE HIGHER YOUR SCORE, \n          THE MORE COLORS THAT APPEAR. \n                CHOOSE THE COLOR TO USE \n               OR JUST CLICK THE SQUARES \n                      TO CHOOSE A COLOR.");
        instructionsTA.setAutoscrolls(false);
        instructionsTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 211, 28), 3));
        instructionsTA.setDisabledTextColor(new java.awt.Color(245, 211, 28));
        instructionsTA.setFocusable(false);
        instructionsTA.setSelectionColor(new java.awt.Color(0, 0, 0));
        instructionsScroll.setViewportView(instructionsTA);

        javax.swing.GroupLayout framePanelLayout = new javax.swing.GroupLayout(framePanel);
        framePanel.setLayout(framePanelLayout);
        framePanelLayout.setHorizontalGroup(
            framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePanelLayout.createSequentialGroup()
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, framePanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(okayBTN))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, framePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instructionsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        framePanelLayout.setVerticalGroup(
            framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructionsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okayBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayBTNActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_okayBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlayPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlayPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlayPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlayPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToPlayPattern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup exitGroup;
    private javax.swing.JPanel framePanel;
    private javax.swing.JScrollPane instructionsScroll;
    private javax.swing.JTextArea instructionsTA;
    private javax.swing.JButton okayBTN;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
