/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2ndquarterproject;
import java.util.Random;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author Asus
 */
public class PatternHomeScreen extends javax.swing.JFrame {
    int delay = 5000;
    int[][] colors = {{245,211,28},{255,0,0},{0,176,80},{0,176,240},{255,255,255},{237,125,49},{112,48,160},{250,126,232},{128,128,128},{0,0,0}};
    int[] btnCheck = new int[9];
    int[] ctrChecker = {0,100,100,100,100,100,100,100,100,100};
    int colorCounter = 9;
    int selected = 0;
    int ctr1 = 1,ctr2 = 1,ctr3 = 1,ctr4 = 1,ctr5 = 1,ctr6 = 1,ctr7 = 1,ctr8 = 1,ctr9 = 1;
    int score = 0;
    int wrongColor = 0;
    int playAgain = 0;
    
    /**
     * Creates new form GameHomeScreen
     */
    public PatternHomeScreen() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        startBTN = new javax.swing.JButton();
        helpBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        framePanel.setBackground(new java.awt.Color(42, 42, 52));

        titlePanel.setBackground(new java.awt.Color(27, 28, 33));
        titlePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titleLabel.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(245, 211, 28));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("PATTERN ATTACK");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        startBTN.setBackground(new java.awt.Color(245, 211, 28));
        startBTN.setFont(new java.awt.Font("Source Sans Pro Black", 1, 24)); // NOI18N
        startBTN.setText("START");
        startBTN.setToolTipText("");
        startBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        startBTN.setFocusPainted(false);
        startBTN.setPreferredSize(new java.awt.Dimension(79, 35));
        startBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBTNActionPerformed(evt);
            }
        });

        helpBTN.setBackground(new java.awt.Color(245, 211, 28));
        helpBTN.setFont(new java.awt.Font("Source Sans Pro Black", 1, 24)); // NOI18N
        helpBTN.setText("HOW TO PLAY");
        helpBTN.setToolTipText("");
        helpBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        helpBTN.setFocusPainted(false);
        helpBTN.setPreferredSize(new java.awt.Dimension(79, 35));
        helpBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(245, 211, 28));
        exitBTN.setFont(new java.awt.Font("Source Sans Pro Black", 1, 24)); // NOI18N
        exitBTN.setText("EXIT");
        exitBTN.setToolTipText("");
        exitBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exitBTN.setFocusPainted(false);
        exitBTN.setPreferredSize(new java.awt.Dimension(79, 35));
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout framePanelLayout = new javax.swing.GroupLayout(framePanel);
        framePanel.setLayout(framePanelLayout);
        framePanelLayout.setHorizontalGroup(
            framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePanelLayout.createSequentialGroup()
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(framePanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(helpBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        framePanelLayout.setVerticalGroup(
            framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBTNActionPerformed
        this.setVisible(false);
        new PatternAttack().setVisible(true);
        PatternAttack.checkBTN.setVisible(false);
        PatternAttack.clearBTN.setVisible(false);
        PatternAttack.whiteBTN.setEnabled(false);
        PatternAttack.orangeBTN.setEnabled(false);
        PatternAttack.violetBTN.setEnabled(false);
        PatternAttack.pinkBTN.setEnabled(false);
        PatternAttack.greyBTN.setEnabled(false);
        PatternAttack.blackBTN.setEnabled(false);
    }//GEN-LAST:event_startBTNActionPerformed

    private void helpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBTNActionPerformed
        new HowToPlayPattern().setVisible(true);
    }//GEN-LAST:event_helpBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        new Exit().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitBTNActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        PatternHomeScreen game = new PatternHomeScreen();
        java.awt.EventQueue.invokeLater(() -> {
            new PatternHomeScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton exitBTN;
    private javax.swing.JPanel framePanel;
    public static javax.swing.JButton helpBTN;
    public static javax.swing.JButton startBTN;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
